name: Build EXE

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build CN
        run: |
          pyinstaller ^
            --onefile ^
            --name LN1Analyzer_CN ^
            osu_mania_4k_ln_analyzer_CN.py

      - name: Build EN
        run: |
          pyinstaller ^
            --onefile ^
            --name LN1Analyzer_EN ^
            osu_mania_4k_ln_analyzer_EN.py

      - name: Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/LN1Analyzer_CN.exe
            dist/LN1Analyzer_EN.exe